# Generated by Django 4.0.3 on 2022-05-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=55)),
                ('bio', models.TextField(default='Hello! My name is {name}', max_length=400)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('photo', models.URLField(blank=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_from_whom', to='member.account')),
                ('liked', models.ManyToManyField(blank=True, to='member.account')),
            ],
        ),
    ]
